version: '3.3'
services:
  backend:
    build: .
    image: cscoupler
    restart: always
    ports:
      - 3000:3000
  frontend:
    build: ./cscoupler-client
    image: cscoupler-client
    ports: 
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cscoupler
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql