version: '3.3'
services:
  frontend:
    build: ./cscoupler-client
    hostname: cscoupler
    image: cscoupler-client
    ports: 
      - 8080:80
  backend:
    build: .
    image: cscoupler
    depends_on: 
      - db
    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cscoupler
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql